

services:

  #  вэбсервер
  nginx:
    image: nginx:1.25
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./:/var/www/html/
    ports:
      - "8080:80"
    restart: always
    networks:
      - webasyst

  #   использование своего собственного образа для php8.3-fpm c composer
  php8.3-fpm:
    image: php8.3-fpm-deb:composer
    volumes:
      - ./:/var/www/html/
    restart: always
    networks:
      - webasyst

  #   контейнер с базой данный MySQL. Файлы базы прокинуты снаружи из каталога ./db
  mysql:
    image: mysql:8.0.37
    volumes:
      - ./db/:/var/lib/mysql
#    ports:
#      - "8060:3306"
    restart: always
#    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: 1234567
        MYSQL_DATABASE: admin
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
    networks:
      - webasyst


  phpmyadmin:
      image: phpmyadmin:5.2.1-apache
      links:
          - mysql
      restart: always
      ports:
          - "8060:80"
      environment:
          - MY_SQL_ROOT_PASSWORD=1234567
          - PMA_ARBITRARY=1
          - PMA_HOST=mysql
          - PMA_USER=admin
          - PMA_PASSWORD=admin
      networks:
          - webasyst

#  elasticsearch:
#      image: elasticsearch:8.14.0
#      restart: always
#      ports:
#          - 9200:9200
#          - 9300:9300
#      environment:
#          - discovery.type=single-node
#          - bootstrap.memory_lock=true
#      volumes:
#          - elasticsearch:/usr/share/elasticsearch
#      networks:
#          - wiki-app

#  nodejs:
#      image: node:22.0.0-alpine
#      volumes:
#          - ./:/var/www/html/
##      restart: always
#      networks:
#          - crm-lara

#  redis:
#      image: redis:6.0
#      restart: always
#      networks:
#          - wiki-app

networks:
  webasyst:
    name: webasyst

#volumes:
#  elasticsearch:
